# Chem
class Monomer:
    def __init__(id: int, size: float): ...
    @property
    def id(self) -> int: ...
    @property
    def size(self) -> float: ...

class Block:
    def __init__(monomer: Monomer, repeat_units: int, segment_length: float): ...
    @property
    def monomer(self) -> Monomer: ...
    @property
    def repeat_units(self) -> int: ...
    @property
    def segment_length(self) -> float: ...

class Species: ...
class Point: ...
class Polymer: ...

# Domain
class Mesh:
    def __init__(*dimensions: int): ...

class UnitCell: ...
class LamellarCell: ...
class SquareCell: ...
class CubicCell: ...

# System
class System:
    def __init__(mesh: Mesh, cell: UnitCell, species: list[Species]): ...

class FieldUpdater:
    def __init__(system: System, step_size: float): ...
    def step(self, system: System) -> None: ...
