import numpy as np

class Monomer:
    def __init__(id: int, size: float): ...
    @property
    def id(self) -> int: ...
    @property
    def size(self) -> float: ...

class Block:
    def __init__(monomer: Monomer, repeat_units: int, segment_length: float): ...
    @property
    def monomer(self) -> Monomer: ...
    @property
    def repeat_units(self) -> int: ...
    @property
    def segment_length(self) -> float: ...

class Species: ...
class Point: ...
class Polymer: ...

class Mesh:
    def __init__(*dimensions: int): ...

class UnitCell: ...
class LamellarCell: ...
class SquareCell: ...
class Hexagonal2DCell: ...
class CubicCell: ...

class System:
    def __init__(mesh: Mesh, cell: UnitCell, species: list[Species]): ...
    def fields(self) -> dict[int, np.ndarray]: ...
    def concentrations(self) -> dict[int, np.ndarray]: ...
    def field_error(self) -> float: ...
    def free_energy(self) -> float: ...
    def free_energy_bulk(self) -> float: ...
    def stress(self) -> np.ndarray: ...
    def set_interaction(self, i: int, j: int, chi: float) -> None: ...
    def sample_fields(self, scale: float) -> None: ...
    def update(self) -> None: ...

class FieldUpdater:
    def __init__(system: System, step_size: float): ...
    def step(self, system: System) -> None: ...

class CellUpdater:
    def __init__(system: System, step_size: float): ...
    def step(self, system: System) -> None: ...
