import numpy as np
from numpy.typing import NDArray

class Monomer:
    def __init__(id: int, size: float): ...
    @property
    def id(self) -> int: ...
    @property
    def size(self) -> float: ...

class Block:
    def __init__(monomer: Monomer, repeat_units: int, segment_length: float): ...
    @property
    def monomer(self) -> Monomer: ...
    @property
    def repeat_units(self) -> int: ...
    @property
    def segment_length(self) -> float: ...

class Species:
    @property
    def size(self) -> float: ...
    def monomers(self) -> list[Monomer]: ...
    def monomer_fraction(self, id: int) -> float: ...

class Point(Species): ...
class Polymer(Species): ...

class Mesh:
    def __init__(*dimensions: int): ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dimensions(self) -> list[int]: ...

class UnitCell:
    @property
    def ndim(self) -> int: ...
    @property
    def volume(self) -> float: ...
    @property
    def parameters(self) -> NDArray[np.floating]: ...
    @property
    def shape(self) -> NDArray[np.floating]: ...

class LamellarCell(UnitCell): ...
class SquareCell(UnitCell): ...
class Hexagonal2DCell(UnitCell): ...
class CubicCell(UnitCell): ...

class System:
    def __init__(mesh: Mesh, cell: UnitCell, species: list[Species]): ...
    @property
    def cell(self) -> UnitCell: ...
    @property
    def mesh(self) -> Mesh: ...
    def fields(self) -> dict[int, NDArray[np.floating]]: ...
    def concentrations(self) -> dict[int, NDArray[np.floating]]: ...
    def free_energy(self) -> float: ...
    def free_energy_bulk(self) -> float: ...
    def stress(self) -> NDArray[np.floating]: ...
    def field_error(self) -> float: ...
    def stress_error(self) -> float: ...
    def set_interaction(self, i: int, j: int, chi: float) -> None: ...
    def sample_fields(self, *, scale: float = 0.05, seed: int | None = None) -> None: ...
    def update(self) -> None: ...

class FieldUpdater:
    def __init__(system: System, step_size: float): ...
    def step(self, system: System) -> None: ...

class CellUpdater:
    def __init__(system: System, step_size: float): ...
    def step(self, system: System) -> None: ...
